"use client";

import {
  AlertTriangle,
  CircleDot,
  Lightbulb,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { Insight } from "@/lib/analytics";
import { cn } from "@/lib/utils";

const TONE: Record<Insight["tone"], { icon: LucideIcon; className: string }> = {
  positive: { icon: Sparkles, className: "text-health-excellent" },
  neutral: { icon: CircleDot, className: "text-health-on-track" },
  warning: { icon: AlertTriangle, className: "text-health-behind" },
};

/** Narrative takeaways generated by `buildInsights`. */
export function InsightsCard({ insights }: { insights: Insight[] }) {
  return (
    <Card className="h-full">
      <CardHeader>
        <div>
          <CardTitle className="flex items-center gap-1.5">
            <Lightbulb className="size-3.5 text-health-slipping" />
            Productivity insights
          </CardTitle>
          <CardDescription>
            Patterns worth acting on from the last 30 days
          </CardDescription>
        </div>
      </CardHeader>

      <CardContent>
        <ul className="space-y-3.5">
          {insights.slice(0, 5).map((insight) => {
            const tone = TONE[insight.tone];
            return (
              <li key={insight.id} className="flex gap-2.5">
                <tone.icon className={cn("mt-0.5 size-4 shrink-0", tone.className)} />
                <div className="space-y-0.5">
                  <p className="text-xs font-medium">{insight.title}</p>
                  <p className="text-xs leading-relaxed text-muted-foreground">
                    {insight.detail}
                  </p>
                </div>
              </li>
            );
          })}
        </ul>
      </CardContent>
    </Card>
  );
}
