/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeevaRouteImport } from './routes/meeva'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace/$slug'
import { Route as SoonIndexRouteImport } from './routes/soon/index'
import { Route as SoonSlugRouteImport } from './routes/soon/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeevaRoute = MeevaRouteImport.update({
  id: '/meeva',
  path: '/meeva',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonIndexRoute = SoonIndexRouteImport.update({
  id: '/soon/',
  path: '/soon/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonSlugRoute = SoonSlugRouteImport.update({
  id: '/soon/$slug',
  path: '/soon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeva': typeof MeevaRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/soon/': typeof SoonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeva': typeof MeevaRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/soon': typeof SoonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeva': typeof MeevaRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/soon/': typeof SoonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meeva'
    | '/marketplace/$slug'
    | '/soon/$slug'
    | '/marketplace/'
    | '/soon/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meeva'
    | '/marketplace/$slug'
    | '/soon/$slug'
    | '/marketplace'
    | '/soon'
  id:
    | '__root__'
    | '/'
    | '/meeva'
    | '/marketplace/$slug'
    | '/soon/$slug'
    | '/marketplace/'
    | '/soon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeevaRoute: typeof MeevaRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  SoonSlugRoute: typeof SoonSlugRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  SoonIndexRoute: typeof SoonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeva': {
      id: '/meeva'
      path: '/meeva'
      fullPath: '/meeva'
      preLoaderRoute: typeof MeevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon/': {
      id: '/soon/'
      path: '/soon'
      fullPath: '/soon/'
      preLoaderRoute: typeof SoonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon/$slug': {
      id: '/soon/$slug'
      path: '/soon/$slug'
      fullPath: '/soon/$slug'
      preLoaderRoute: typeof SoonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeevaRoute: MeevaRoute,
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  SoonSlugRoute: SoonSlugRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  SoonIndexRoute: SoonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
