export type SkillAccent = 'orange' | 'teal' | 'blue' | 'green' | 'purple'

export const portfolio = {
  name: 'Drizz',
  mark: 'DRZ.',
  domain: 'drizz.dev',
  title: 'Drizz — freelance software developer',
  headline: "HELLO, I'M",
  nameAccent: 'DRIZZ.',
  roles: [
    'Full-stack developer',
    'Product engineer',
    'Freelance software developer',
  ],
  openToWork: true,
  summary: [
    'I design and ship software people actually use — products under Meeva, and freelance work for teams that need something built well.',
    'Some of that is new. Some of it replaces a tool you already have. All of it is meant to stay.',
    'Currently open for freelance and contract work.',
  ],
  email: 'hello@drizz.dev',
  resumeHref: '/#work',
  socials: [
    {
      label: 'GitHub',
      href: 'https://github.com/idrisifeoluwa',
      id: 'github' as const,
    },
  ],
  ticker: [
    { label: 'STATUS', value: 'OPEN TO WORK', delta: '+AVAILABLE' },
    { label: 'ROLE', value: 'FULL STACK', delta: 'PRODUCT' },
    { label: 'STUDIO', value: 'MEEVA', delta: 'HQ' },
    { label: 'STACK', value: 'REACT / NODE', delta: 'TS' },
    { label: 'WORK', value: 'FREELANCE', delta: 'CONTRACT' },
    { label: 'FOCUS', value: 'SHIPPING', delta: 'UI + API' },
  ],
  tools: [
    { label: 'TypeScript', id: 'code' as const },
    { label: 'React', id: 'browser' as const },
    { label: 'Node', id: 'terminal' as const },
    { label: 'Postgres', id: 'database' as const },
    { label: 'Product', id: 'cube' as const },
    { label: 'Ship', id: 'lightning' as const },
  ],
  competencies: [
    {
      title: 'Full Stack',
      tone: 'green' as const,
      tags: ['NEXT.JS', 'REACT 19', 'TYPESCRIPT', 'NODE.JS'],
      copy: 'Interfaces, APIs, and the data behind them — shipped as one product, not a pile of demos.',
    },
    {
      title: 'Product Engineer',
      tone: 'purple' as const,
      tags: ['VITE', 'TANSTACK', 'TAILWIND', 'POSTGRES'],
      copy: 'I shape the thing as I build it: structure, copy, and the path a person actually takes through the app.',
    },
    {
      title: 'Problem Solving',
      tone: 'yellow' as const,
      tags: ['SYSTEMS', 'AUTH', 'APIS', 'SHIPPING'],
      copy: 'Cut the work to what matters, pick a stack that will last, and leave it in a state someone else can run.',
    },
  ],
  experience: [
    {
      role: 'Freelance Software Developer',
      org: '@Open to work',
      dates: 'Present',
      industry: 'Product & services',
      href: 'mailto:hello@drizz.dev',
      bullets: [
        'Available for freelance and contract work: new products, rebuilds, and the unglamorous last mile of shipping.',
        'Comfortable owning UI through API and data — React, TypeScript, Node, and Postgres.',
      ],
    },
    {
      role: 'Founder',
      org: '@Meeva',
      dates: '2026 — Present',
      industry: 'Software studio',
      href: '/meeva',
      bullets: [
        'Building Meeva as a public house for live products and a shareable list for what is next.',
        'Shipped the company headquarters, marketplace, and coming-soon flow as a reusable freelance base.',
      ],
    },
    {
      role: 'Product work',
      org: '@Selected builds',
      dates: 'Ongoing',
      industry: 'Apps & sites',
      bullets: [
        'lockIn by meeva — a personal focus system (Next.js, Supabase).',
        'Ashlove — a nursing consultation site. AuraDesk — a commerce template.',
        'Shared Express + Prisma backend with email and Google sign-in in progress.',
      ],
    },
  ],
  skills: [
    {
      id: 'typescript',
      name: 'TypeScript',
      category: 'Language',
      level: 'Core',
      years: 'Daily',
      holder: 'Drizz',
      accent: 'blue' as SkillAccent,
    },
    {
      id: 'react',
      name: 'React',
      category: 'Interface',
      level: 'Core',
      years: 'Daily',
      holder: 'Drizz',
      accent: 'teal' as SkillAccent,
    },
    {
      id: 'next',
      name: 'Next.js',
      category: 'Web',
      level: 'Strong',
      years: 'Shipping',
      holder: 'Drizz',
      accent: 'green' as SkillAccent,
    },
    {
      id: 'node',
      name: 'Node.js',
      category: 'API',
      level: 'Strong',
      years: 'Shipping',
      holder: 'Drizz',
      accent: 'orange' as SkillAccent,
    },
    {
      id: 'postgres',
      name: 'Postgres',
      category: 'Data',
      level: 'Working',
      years: 'In use',
      holder: 'Drizz',
      accent: 'purple' as SkillAccent,
    },
  ],
  pipeline: [
    {
      step: '01',
      title: 'Listen',
      copy: 'What has to exist, who it is for, and what “done” actually looks like.',
    },
    {
      step: '02',
      title: 'Shape',
      copy: 'Structure, interface, and the smallest version that is still the real product.',
    },
    {
      step: '03',
      title: 'Build',
      copy: 'Ship the thing. UI, API, data — in a state you can run and change.',
    },
    {
      step: '04',
      title: 'Stay',
      copy: 'Fix what shows up after launch. Leave it quieter than I found it.',
    },
  ],
  work: [
    {
      name: 'Meeva',
      kind: 'Company HQ',
      copy: 'The house for live products and a shareable list of what is next.',
      href: '/meeva',
      internal: true,
    },
    {
      name: 'lockIn',
      kind: 'Product',
      copy: 'A personal focus system. lockIn by meeva.',
    },
    {
      name: 'Ashlove',
      kind: 'Client site',
      copy: 'Nursing consultation site — booking and the public face of the practice.',
    },
    {
      name: 'AuraDesk',
      kind: 'Template',
      copy: 'A Next.js commerce starter for storefront work.',
    },
  ],
} as const
